# Generated by Django 4.1.7 on 2023-02-28 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api', models.CharField(max_length=255)),
                ('resource', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('filepath', models.FileField(upload_to='starwars/media/collections/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
